production:
  adapter: mysql2
  database: siwei_cms
  username: root
  password: ""
  host: localhost
  encoding: utf8

development:
  adapter: mysql2
  database: siwei_cms
  username: root
  password: ""
  host: localhost
  encoding: utf8
