---
chdir: /home/siwei/personal_site
environment: production
address: 0.0.0.0
port: 3501
timeout: 30
#log: /log/thin.log
#pid: /var/www/discourse/shared/pids/thin.pid
#socket: /var/www/discourse/tmp/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 2
daemonize: true
